### ISSUE TITLE
Focusing on Contrast tab throws with 0-valued images

### ISSUE THREAD

**Issue by cpoczatek** [BWHCNI/OpenMIMS#25]
Triggered by but not strictly related to interleaved images.

To reproduce:
- Open any file
- Select 1st image
- Edit->Select All & Edit->cut to set all pixels to zero
- Click on Contrast tab

```
/nrims/home3/cpoczatek/test_images/elec_peak_switch/130604-c8-low-PC-15N-D-velli-interleaved.nrrd
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Requires xLow < xHigh.
    at org.jfree.chart.renderer.RendererUtilities.findLiveItemsLowerBound(RendererUtilities.java:76)
    at org.jfree.chart.renderer.RendererUtilities.findLiveItems(RendererUtilities.java:261)
    at org.jfree.chart.plot.XYPlot.render(XYPlot.java:3819)
    at com.nrims.plot.MimsXYPlot.draw(MimsXYPlot.java:294)
    at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1237)
    at org.jfree.chart.ChartPanel.paintComponent(ChartPanel.java:1677)
    at javax.swing.JComponent.paint(JComponent.java:1056)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
    at javax.swing.JComponent.paintChildren(JComponent.java:889)
    at javax.swing.JComponent.paint(JComponent.java:1065)
```

**Comment by taylorwrt** [comment]
If all pixels get sets to zero, JFreeChart fails because in this case, the xAsis low and high values are both zero.  This bug has now been prevented by forcing xAxis high to always be non-zero.
