### ISSUE TITLE
Interleaved and Mosaic

### ISSUE THREAD

**Issue by cguillermier** [BWHCNI/OpenMIMS#30]
- when interleaved on mosaic there is the following error message popping up:

`Just set currentlyOpeningImages to false
FileOpenTask is finished.
/home/cg/Desktop/mosaic-160823-c7-A1-M5-interleaved.nrrd
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: [S cannot be cast to [F
    at ij.io.ImageWriter.writeFloatStack(ImageWriter.java:190)
    at ij.io.ImageWriter.write(ImageWriter.java:290)
    at com.nrims.data.Nrrd_Writer.writeImage(Nrrd_Writer.java:129)
    at com.nrims.data.Nrrd_Writer.save(Nrrd_Writer.java:96)
    at com.nrims.UI.saveSession(UI.java:2589)
    at com.nrims.MimsStackEditor.interleaveButtonActionPerformed(MimsStackEditor.java:2217)
    at com.nrims.MimsStackEditor.access$1200(MimsStackEditor.java:56)
    at com.nrims.MimsStackEditor$13.actionPerformed(MimsStackEditor.java:1689)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6535)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6300)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2750)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by cguillermier** [comment]
test file: /nrims/data/MIMS_DATA/STEINHAUSER/Cox-Liver-Exp1/mosaic-160823-c7-A1-M5.nrrd

**Comment by taylorwrt** [comment]
This exception was caused by a bug in the interleave method of MimsStackEditor.java.   The proper execution of this method depends on the ability to determine whether the pixel values in the selected file are 16 bit integers or floating point values, and that capability was not there.   I added a check for this, which results in the proper processor being used to do the interleaving.
