### ISSUE TITLE
Interleaved mosaic file

### ISSUE THREAD

**Issue by cguillermier** [BWHCNI/OpenMIMS#32]
when opening the created interleaved file here is what we get:
![screenshot from 2016-09-07 10-32-53](https://cloud.githubusercontent.com/assets/19674515/18315855/7aab820a-74e6-11e6-8224-56f487c3190b.png)
`-------------------------------------------------
java.io.IOException
    at com.nrims.data.Nrrd_Reader.getPixels(Nrrd_Reader.java:428)
    at com.nrims.UI$FileOpenTask.loadMIMSFileInBackground(UI.java:6695)
    at com.nrims.UI$FileOpenTask.openFile(UI.java:6378)
    at com.nrims.UI$FileOpenTask.doInBackground(UI.java:6277)
    at com.nrims.UI$FileOpenTask.doInBackground(UI.java:6089)
    at com.nrims.UI$FileOpenTask.doInBackground(UI.java:6052)
    at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at javax.swing.SwingWorker.run(SwingWorker.java:334)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Just set currentlyOpeningImages to false
FileOpenTask is finished.`

**Comment by taylorwrt** [comment]
I am not certain why, but in fixing bugs 30 and/or 31, I seem to have fixed this bug as well.
